// File generated by FlutterFire CLI & customized for project.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO1vSm0sXYvyMJT0YnpQNvn60CqDhc08M',
    appId: '1:530452506731:web:6fa76cbe09cc705f67a92e',
    messagingSenderId: '530452506731',
    projectId: 'coffee-spark-ai-barista-5e2cd',
    storageBucket: 'coffee-spark-ai-barista-5e2cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO1vSm0sXYvyMJT0YnpQNvn60CqDhc08M',
    appId: '1:530452506731:android:6fa76cbe09cc705f67a92e',
    messagingSenderId: '530452506731',
    projectId: 'coffee-spark-ai-barista-5e2cd',
    storageBucket: 'coffee-spark-ai-barista-5e2cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO1vSm0sXYvyMJT0YnpQNvn60CqDhc08M',
    appId: '1:530452506731:ios:6fa76cbe09cc705f67a92e',
    messagingSenderId: '530452506731',
    projectId: 'coffee-spark-ai-barista-5e2cd',
    storageBucket: 'coffee-spark-ai-barista-5e2cd.firebasestorage.app',
    iosBundleId: 'com.artable',
  );
}
